# Generated by Django 5.0.1 on 2024-04-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scube_ss',
            name='new_pr',
            field=models.CharField(blank=True, choices=[('NEW', 'NEW')], max_length=50, null=True),
        ),
    ]
