# Generated by Django 5.2.12 on 2026-05-03 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_scube_ss_new_pr'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='scube_ss',
            name='status',
            field=models.CharField(choices=[('SCUBE', 'SCUBE'), ('THIRUVALLA', 'THIRUVALLA'), ('SALE', 'SALE'), ('S-CUBE-DT', 'S-CUBE-DT'), ('ORDER', 'ORDER')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Item Code')),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prize')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.materialname', verbose_name='Material Name')),
            ],
        ),
    ]
