# Generated by Django 5.2.12 on 2026-05-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_sofaproductionrecord_productionmaterialitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sofaproductionrecord',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
