# Generated by Django 5.2.12 on 2026-05-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_sofaproductionrecord_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='sofaproductionrecord',
            name='sofa_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sofaproductionrecord',
            name='sofa_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sofaproductionrecord',
            name='sofa_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
