# Generated by Django 5.2.12 on 2026-05-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_sofaproductionrecord_sofa_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoardMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
