# Generated by Django 5.2.12 on 2026-05-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_boardcolor_boardmaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pb_category', models.CharField(choices=[('CUPBOARD', 'CUPBOARD'), ('TABLE', 'TABLE'), ('BEDROOM-SET', 'BEDROOM-SET'), ('POOJA-STAND', 'POOJA-STAND'), ('TV-STAND', 'TV-STAND'), ('SOFA', 'SOFA'), ('OTHERS', 'OTHERS'), ('ORDER', 'ORDER')], max_length=50, verbose_name='Category')),
                ('pb_name', models.CharField(max_length=150, unique=True, verbose_name='Product Name')),
                ('pb_size', models.CharField(blank=True, max_length=100, null=True, verbose_name='Size')),
                ('pb_material', models.CharField(blank=True, max_length=100, null=True, verbose_name='Material')),
                ('pb_wage', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Wage')),
                ('pb_prize', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prize')),
                ('pb_description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
    ]
