# Generated by Django 5.2.12 on 2026-05-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_productitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('cl_Catogory', models.CharField(blank=True, max_length=50, null=True)),
                ('cl_name', models.CharField(blank=True, max_length=150, null=True)),
                ('cl_size', models.CharField(blank=True, max_length=100, null=True)),
                ('cl_prize', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cl_wage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cl_material', models.CharField(blank=True, max_length=100, null=True)),
                ('cl_color', models.CharField(blank=True, max_length=100, null=True)),
                ('cl_pr_date', models.DateField(blank=True, null=True)),
                ('cl_status', models.CharField(default='SCUBE', max_length=50)),
                ('cl_image', models.ImageField(blank=True, null=True, upload_to='board_images/')),
            ],
        ),
    ]
