# Generated by Django 5.2.12 on 2026-05-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_boardproductionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardproductionrecord',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
