# Generated by Django 5.2.12 on 2026-05-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_boardproductionrecord_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='PB_Paid_Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('payment_mode', models.CharField(choices=[('CASH', 'CASH'), ('GPAY', 'GPAY')], default='CASH', max_length=10, verbose_name='Payment Mode')),
            ],
        ),
    ]
