# Generated by Django 5.2.12 on 2026-06-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_sofa_paid_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='scube_ss',
            name='gallery_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('SHOW', 'SHOW'), ('UNSHOW', 'UNSHOW')], default='PENDING', max_length=20),
        ),
    ]
