# Generated by Django 5.2.12 on 2026-06-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_scube_ss_gallery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scube_ss',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
