# Generated by Django 5.2.12 on 2026-07-02 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_invoice_invoiceitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('SOFA', 'SOFA MATERIAL'), ('PB', 'PB MATERIAL')], max_length=20, verbose_name='Material Type')),
                ('category_name', models.CharField(max_length=100, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Item Name')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color')),
                ('size', models.CharField(blank=True, max_length=50, null=True, verbose_name='Size')),
                ('prize', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prize')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock Quantity')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stock_images/', verbose_name='Image')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='manager.stockmaterialcategory', verbose_name='Select Material')),
            ],
        ),
    ]
