# Generated by Django 5.2.12 on 2026-07-16 08:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_stockmaterialcategory_stockitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoPrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dummy_text', models.TextField()),
                ('is_printed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='scube_ss',
            name='status',
            field=models.CharField(choices=[('SCUBE', 'SCUBE'), ('THIRUVALLA', 'THIRUVALLA'), ('GALLERY', 'GALLERY'), ('S-CUBE-DT', 'S-CUBE-DT'), ('ORDER', 'ORDER'), ('WORKSHOP', 'WORKSHOP')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('adjustment_type', models.CharField(choices=[('IN', 'STOCK IN'), ('OUT', 'STOCK OUT')], max_length=3)),
                ('quantity', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='manager.stockitem')),
            ],
        ),
    ]
